name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'un-valor-para-que-no-de-error'
    
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy
      run: |
        ssh ubuntu@${{ secrets.SSH_HOST }} '
          if [ ! -d 'HelloWorld' ]; then
            git clone https://github.com/cenizojr/HelloWorld.git;
          else
            cd HelloWorld && git stash && git fetch --all && git reset --hard origin/main && git pull origin main;
          fi
          if pgrep node; then
            forever stopall;
          fi
          cd HelloWorld && npm install
          cd HelloWorld && forever start src/main.js
        '